config/routes.rb
Truthpage::Application.routes.draw do 
  
  match '/signin',  :to => 'sessions#new'
  match '/login',  :to => 'sessions#JSnew'
  match '/newlogin', :to => 'sessions#JScreate'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/welcome', :to => 'pages#welcome_page'
  match '/contact', :to => 'pages#contact'
  match '/home',   :to => 'pages#home'
  match '/about',  :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/legal',    :to => 'pages#legal'
  match '/privacy',    :to => 'pages#privacy'
  match '/terms',    :to => 'pages#terms'
  match '/help',    :to => 'pages#help'
  match '/admin', :to => 'admin/users#index'
  match '/',        :to => 'pages#home'
  match '/tickertest', :to=>'pages#tickertest'
  match "/auth/:provider/callback" => "authentications#create"
  match "/auth/failure" => "authentications#auth_failure"
  match "/search", :to=> "users#index", :as=>"search" 
  match '/activate/:id/:activation_code', :to=>"users#activation", :as=>"activate"
  match "/assist", :to=>"users#assist", :as=>"assist"
  match "/reset/:id/:reset_code", :to=>"users#reset", :as=>"reset"
  match "/activate_user/:id", :to=>"users#activate", :as=>"activate_user"
  match "/welcome_user/:id", :to=>"users#welcome", :as=>"welcome_user"
  match "complete_session_authentication_path", :to=>"authentications#complete_session_authentication", :as=>:complete_session_authentication
             
  resources :microposts do
    collection do
      post :create_pending
    end
    resources :comments
  end
  resources :users do
      member do
        post :follow
        post :unfollow
        get :following, :followers
        delete :remove_background
        delete :remove_photo
        delete :deactivate_profile
      end
  end
  resources :notifications, :only=>[:create, :destroy] do
    collection do
      delete :clear_all
    end
  end
  resources :ratings, :only => [:create, :destroy]
  resources :authentications
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :comments, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  namespace :admin do
    resources :users
  end

  controller :users do
    match ':id' => :show, :via => :get, :constraints => { :id => /[A-Za-z0-9\-\_\+]+/ }
  end

  root :to => 'pages#home'

end

app/models/user.rb
require 'active_support/secure_random'
class User < ActiveRecord::Base

  has_many :sent_notifications, :foreign_key=>"sender_id", :class_name=>"Notification", :dependent => :destroy
  has_many :received_notifications, :foreign_key=>"receiver_id", :class_name=>"Notification", :dependent => :destroy
  has_many :authentications, :dependent => :destroy
  has_many :identities, :through=>:authentications
  has_many :microposts, :dependent => :destroy
  has_many :received_microposts, :foreign_key=>"belongs_to_id", :class_name=>"Micropost", :dependent=>:destroy
  has_many :relationships, :foreign_key => "follower_id",
                             :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                     :class_name => "Relationship",
                                     :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  has_attached_file :photo,
                    :styles => {
                    :tiny => "25x25#",
                    :thumb=> "50x50#",
                    :medium=> "100x100#",
                    :small  => "220x220>" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :path => "/:style/:id/:filename" 
  has_attached_file :background,
                    :styles => {
                    :medium=> "100x100#",
                    :small  => "220x220>" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :path => "/:style/:id/:filename" 

  validates :username, :length=>{:minimum => 3}, :uniqueness=>true, :format=>{ :with => /^[-\w\._@]+$/i, :message => "should only contain letters, numbers, or .-_@"}
  validates :email, :uniqueness=>true, :format=>{:with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, :message => "we need a valid email address!"}
  validates :password, :length=>{:minimum => 4}, :on => :create, :unless=>Proc.new{|u| u.service_mode?}                
  validates_confirmation_of :password
  
  attr_accessor :password, :mode

  before_save :prepare_password

  default_scope where("users.deleted_at IS NULL")
  scope :created_order, order("users.created_at DESC")

  def destroy
   update_attribute(:deleted_at, Time.now.utc)
   run_callbacks(:destroy) #explicitly run the destroy callbacks to set dependents attribute
  end                  
  
  def service_mode?
    mode=="service"
  end

  def to_param
    username
  end                   
  
  def self.search(search)
   if search
      where('username LIKE LOWER(?) OR email LIKE LOWER(?)', "%#{search.downcase}%","%#{search.downcase}%")
   else
      all
   end
  end
                    
  #returns the relationship object IF this object is followed by the supplied user argument.                                                                                 
  def following?(user)
    relationships.find_by_followed_id(user)
  end

  #adds a relationship object with this user object and the one supplied in the argument.
  def follow!(user)
    relationships.create!(:followed_id => user.id)
  end

  #deletes a relationship object with this user object and the one supplied in the argument.
  def unfollow!(user)
     relationships.find_by_followed_id(user).destroy
  end

  #returns a boolean if this user object can be followed by the one supplied in the argument.
  def followable_by?(user)
    return false if self.id == user.id #can't follow self
    return false if user.following?(self) #can't follow someone already following
    true #otherwise 
  end
  
  # Auth support
  
  def pending?
    state == 'pending'
  end

  def active?
    # the existence of an activation code means they have not activated yet
    state == 'active' && activation_code.nil?
  end

  def inactive?
    state == 'inactive'
  end

  def activate!
    self.state = 'active'
    self.activated_at = Time.now.utc
    self.activation_code = nil
    save(:validate=>false)
  end

  def inactivate!
    self.state = 'inactive'
    self.activated_at = nil
    self.activation_code = nil
    save(:validate=>false)
  end 

  #generates an activation code and sets state to pending
  def register!
    self.state = "pending"
    self.activation_code = new_code
    self.activated_at = nil    
    save(:validate=>false)
  end

  def new_code
    ActiveSupport::SecureRandom.hex(6)
  end

  # Creates a random code for this user that can be used to reset the user
  # password through the reset and do_reset actions on the controller.
  def make_reset_code
    self.reset_code = new_code
    self.reset_code_at = Time.now.utc
  end


  # Sends an activation email to the user. This email contains a link that
  # allows the user to activate their account. See UserMailer::activation. This method
  # saves this User.
  
  def send_activation_email!
    # Preconditions checked by UserMailer.deliver_activation.
    transaction do
      UserMailer.activation(self).deliver
      self.activation_email_sent_at = Time.now
      self.save!
    end
  end

  # Sends a password reset email to the user. This email contains a link that
  # allows the user to reset the password. See UserMailer::forgot. This method
  # saves this User.
  def send_reset_password_email!
    if self.active? || self.pending?
      transaction do
        make_reset_code
        save!
        UserMailer.forgot(self).deliver
      end
    end
  end

  # Sends a welcome email to the user. This email contains a link that
  # allows the user to reset the password. See UserMailer::forgot. This method
  # saves this User.
  def send_welcome_email!
    if self.active? || self.pending?
      transaction do
        make_reset_code
        save!
        UserMailer.welcome(self).deliver
      end
    end
  end

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = self.where(["username=? OR email=?", login, login]).first
    return user if user && user.matching_password?(pass) && user.active?
  end

  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end
  
  private
  
  def prepare_password
    unless password.blank?
      self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
      self.password_hash = encrypt_password(password)
    end
  end
  
  def encrypt_password(pass)
    Digest::SHA1.hexdigest([pass, password_salt].join)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :admin_login_required
  before_filter :find_user, :except=>[:index]

  def index
    @ratings = Rating.all
    @render_admin_header = true
    @skip_render = true
    @relationships = Relationship.all
    @notifications = Notification.all
    @facebook_users = User.all(:conditions => "facebook_id IS NOT NULL",)
    @users = User.order('created_at DESC').all.paginate(:page => params[:page], :per_page => 40)
    @microposts  = Micropost.all
    @title = "Truthpage | Admin"
  end

  def destroy
    @user = User.find_by_username(params[:id])
    opts = {}
    begin
      User.destroy(@user)
      opts = {:notice=>"User deleted successfully."}
    rescue Exception=>e
      opts = {:error=>"Unable to delete user. #{e.message}"}
    ensure
      redirect_to admin_users_path, opts
    end
  end
  private
 
  def find_user
     @user = User.find_by_username(params[:id])
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  before_filter :login_required, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update, :destroy]
  before_filter :find_user, :only=>[:show, :following, :followers, :follow, :unfollow, :edit, :update, :destroy]
  before_filter :admin_user,   :only => :destroy

  
  def index
    @title = "Truthpage.me"   
  end
  
  def show
    if @user.background.exists?
      @user_custom_background = true
    end
    @top_truths = Micropost.rated.count_order.where(:belongs_to_id => @user.id).limit(3)
    @rating = Rating.new(params[:rating])
    @true_ratings = Rating.where(:owner_id => @user.id, :rating =>"true")
    @total_ratings = Rating.where(:owner_id => @user.id)

    @microposts = Micropost.order.find_all_by_belongs_to_id(@user.id).paginate(:page => params[:page], :per_page => 20)

    @micropost  = @user.microposts.build(params[:micropost])
    @title = " Truthpage.me | #{@user.username}"
    @user = User.find_by_username(params[:id])
    @followers = @user.followers.paginate(:page => params[:page])
    @following = @user.following.paginate(:page => params[:page])
    if current_user
      @comment = Comment.new(params[:comment])
      @notification = Notification.new
    end
  end
   
  def new
    @user = User.new
    @title = "Truthpage.me | Signup"
  end
  
  def create
    @user = User.new(params[:user])
    if simple_captcha_valid?
      if @user.save
        @user.activate!
        flash[:notice] = "Thanks for signing up!"
        sign_in_and_redirect_back_or_default(@user, users_path(@user))
      else
        render :action => 'new'
      end
    else
       flash[:error] = "There was a problem with your info, try again."
       redirect_to signin_path
    end
  end

  def following
    @title = " is following"
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end

  def followers
    @title = "'s followers"
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end

  def follow
    current_user.follow!(@user)
    redirect_to :back, :notice=>"You're now following #{@user.username}!"
    Notification.create!(:sender_id=>current_user.id, :receiver_id=>@user.id, :format=>"is now following you.")
    if @user.try(:follower_email?)
      UserMailer.new_follower_email(@user, current_user).deliver
    end
  end

  def unfollow
    current_user.unfollow!(@user)
    redirect_to :back, :notice=>"You stopped following #{@user.username}."
  end

  def edit
    @title = "Truthpage.me | Settings"
  end

  def remove_photo
    if current_user.photo.exists?
      current_user.photo.destroy
      flash[:notice] = "Your profile picture has been removed."
      redirect_to (:back)
    end
  end

  def remove_background
    if current_user.background.exists?
      current_user.background.destroy
      flash[:notice] = "Your profile background has been removed."
      redirect_to (:back)
    end
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = "Your profile has been updated!"
      redirect_to (:back)
    else
      @title = "Truthpage.me | settings"
      render 'edit'
    end
  end
  
  def destroy
    User.find(@user).destroy
    @user = User.find_by_username(params[:id])
    flash[:success] = "Removed truthpage user."
    redirect_to(:back)
  end

  def deactivate_profile
    current_user.destroy
    session[:user_id] = nil
    flash[:success] = "Your profile has been deactivated."
    redirect_to root_url
  end

  def welcome
    if @user.nil? || (!@user.active? && !@user.pending?)
      flash.now[:error] = "This user is no longer available for this operation."
    else
      @user.send_welcome_email!
      flash[:notice] = "An email has been sent to #{@user.email}."
    end
    redirect_to users_path
  end

  def activation
    #logout_keeping_session!
    @user = User.find_by_id(params[:id])
    code = params[:activation_code]
    case when @user && @user.pending? && @user.activation_code == code
      User.transaction do
        @user.activate!
      end
      flash[:notice] = "Your account is activated! Please log in to continue."
      redirect_to signin_url
    when @user && @user.active?
      flash[:notice] = "Your account is already activated. Please sign in to continue."
      redirect_to signin_url
    else
      flash[:alert]  = "Invalid activation code. Please cut and paste the URL into your browser. If you continue to have trouble, please contact us at #{SUPPORT_EMAIL}."
      redirect_to signin_url
    end
  end

  # If the request's HTTP method was +post+ and a parameter named +email+ is
  # submitted, looks up the corresponding user and, if found, sends a password
  # reset email.
  def assist
    @email = params[:email]
    if request.post? && !@email.blank?
      user = User.find_by_email(@email)
      if user.nil? || (!user.active? && !user.pending?)
        flash.now[:error] = "We don't have an active account for '#{@email}'. Please try again, or contact us at #{SUPPORT_EMAIL} if you need assistance."
      else
        user.send_reset_password_email!
        flash[:notice] = "An email has been sent to #{@email}.<br />".html_safe
        flash[:notice] << "Follow the instructions in the email to reset your password."
        redirect_to signin_url
      end
    end
  end

  def reset
    @user = User.find_by_id(params[:id])
    code = params[:reset_code]
    if request.post?
      if !params[:password].nil?
        @user.password = params[:password]
        @user.password_confirmation = params[:password_confirmation]

        # If the password has already been set, this doesn't normally cause
        # a validation error, but we want it to here.
        if @user.valid? && @user.password.blank?
          @user.errors.add(:password, ActiveRecord::Errors.default_error_messages[:blank])
        end

        if @user.errors.empty?
          @user.reset_code = nil
          @user.reset_code_at = nil
          @user.save!
          if @user.pending?
            User.transaction do
              @user.activate!
            end
          end
          flash[:notice] = "Your password has been changed. Please log in to continue."
          redirect_to signin_url
        end
      else
        render :action=>"reset"
      end
    elsif request.get?
      if @user.blank? || code.blank?
        flash[:error] = "The link from your password reset may have been cut off. Try to copy and paste the entire URL into your browser, or send a new email below. Please contact us at #{SUPPORT_EMAIL} if you continue to have trouble."
        redirect_to assist_url
        return
      end
    end
  end

  #a hard link to activate a user.
  def activate
    @user.activate! if @user.pending?
    redirect_to root_url
  end

  private

  def admin_user
    redirect_to(root_path) if current_user.admin?
  end
  
  def find_user
    @user = User.find_by_username(params[:id])
  end
  
  def correct_user
    @user = find_user
    redirect_to(root_path) unless current_user==@user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def render_follow_links(user)
    return nil if user == current_user
    user.followable_by?(current_user) ? follow_link(user) : unfollow_link(user)
  end

  def follow_link(user, opts={})
    button_to "Follow", follow_user_path(user), :class => 'follow_button'
  end

  def unfollow_link(user, opts={})
    button_to "Unfollow", unfollow_user_path(user), :class => 'unfollow_button'
  end
end

app/views/users/_form.html.erb
<%= form_for @user, :validate => true, :html=> { :multipart => true} do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  
  <div class="settings_fields">
    <div class="formlabel"> Username </div>
    <%= f.text_field :username, :placeholder => "truthpage.me/" :class =>"formfield" %>
  </div>
  <div class="settings_fields">
    <div class="formlabel"> Email </div>
    <%= f.text_field :email, :class =>"formfield" %>
  </div>
  <div class="settings_fields">
    <div class="formlabel"> Password </div>
    <%= f.password_field :password, :class =>"formfield" %>
  </div>
  <div class="settings_fields">
    <div class="formlabel"> Confirm Password </div>
    <%= f.password_field :password_confirmation, :class =>"formfield" %>
  </div>
  <div class="captcha_holder">
	<%= show_simple_captcha :image_style => 'simply_blue', :label => "Type the words in the image." %>
  </div>
  <div class="save_button">
    <%= f.submit 'Sign up', :class => "signup_button" %>
  </div>
  <div class="signup_condition">by clicking sign up you agree to our 
    <%= link_to "terms of use", terms_path, :style=>"color:#555;" %>.
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= render_user_avatar(user, :thumb) %>
  <%= link_to user.username, user %>
  
</li>

app/views/users/assist.html.erb
<h1>Password Assistance</h1>
<p>Enter your email and you will receive a link to reset your password.</p>

<div class="form">
  <%= form_tag do %>
    <div>
    <%= label_tag "email", "Email" %>
    <%= text_field_tag :email, @email, :size => 40, :class =>"formfield" %>
    <%= submit_tag 'Send' %>
    </div>
  <% end -%>
</div>

app/views/users/edit.html.erb
<div class="settings_container">
  <div class="settings_left">
    <div class="settings_header">
      Profile Settings
    </div>
    <%= form_for @user, :html=> { :multipart => true} do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
      <div class="settings_fields">
        <div class="formlabel"> Username </div>
        <%= f.text_field :username, :class =>"formfield" %>
      </div>
      <div class="settings_fields">
        <div class="formlabel"> Email </div>
        <%= f.text_field :email, :class =>"formfield" %>
      </div>
      <div class="settings_fields" >
        <div class="formlabel"> Edit Blurb </div>
	      <%= f.text_area :blurb, :maxlength=>"180", :class=>"settings_blurb" %>
      </div>
      <div class="save_button">
        <%= f.submit 'Save', :class => "savesettings"%>
      </div>
      <div class="photo_container">
        <div class="settings_photo">
          <%= render_user_avatar(current_user, :medium) %>
        </div>
        <div class="formlabel"> Change your picture </div>
          <%= f.file_field :photo %>
        <div class="remover_avatar">
          <% if current_user.photo.exists? %>
            <%= link_to "Remove Profile Picture", {:controller => :users, :action => 'remove_photo' }, :method => :delete, :class => "delete_photo" %>
          <% end %>
        </div>
        <div class="settings_photo">
          <% if current_user.background.exists? %>
            <%= image_tag current_user.background.url(:medium) %>
          <% else %> 
            <%= image_tag "no_profilebg.png" %>
          <% end %>
        </div>
        <div class="formlabel"> Change your background </div>
          <%= f.file_field :background %>
        <div class="remove_background">
          <% if current_user.background.exists? %>
            <%= link_to "Remove Background", {:controller => :users, :action => 'remove_background' }, :method => :delete, :class => "delete_photo" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="settings_bottom">
    <div class="settings_header">
      Account Settings
    </div>
    <%= form_for @user, :html=> { :multipart => true} do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
      <div class="email_settings_h">Email me when:</div>
      <div class="settings_mail">
        <%= f.check_box :mail_subscription, {}, true, false %>
        <%= f.label "Someone posts a new truth about me"%>
      </div>
      <div class="settings_mail">
        <%= f.check_box :follower_email, {}, true, false %>
        <%= f.label "Someone new follows me"%>
      </div>
      <div class="settings_mail">
        <%= f.check_box :rating_email, {}, true, false %>
        <%= f.label "Someone rates a truth about me"%>
      </div>
      <div class="settings_mail">
        <%= f.check_box :comment_email, {}, true, false %>
        <%= f.label "Someone comments on one of my truths"%>
      </div>
      <div class="settings_mail">
        <%= f.check_box :request_email, {}, true, false %>
        <%= f.label "Someone requests a new truth from me"%>
      </div>
      <div class="settings_fields">
        <div class="formlabel"> New Password </div>
        <%= f.password_field :password, :class =>"formfield" %>
      </div>
      <div class="settings_fields">
        <div class="formlabel"> New Password Confirmation </div>
        <%= f.password_field :password_confirmation, :class =>"formfield" %>
      </div>
      <div class="save_button">
        <%= f.submit 'Save', :class => "savesettings" %>
      </div>
    <% end %>
    <div class="delete_profile">
      <div class="formlabel"> Deactivate your account </div>
      <%= link_to "Deactivate Account", {:controller => :users, :action => 'deactivate_profile'}, :method => :delete, :confirm => "Are you sure you want to permanently deactivate your account?", :class=>"deactivate_button" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<strong>Sign up for truthpage.me!</strong>
</p>
Sign up with your Facebook account:
<%= render :partial=>"authentications/services" %>
<p><strong>Already have an account? </strong><%= link_to "Sign in here", signin_url %>.</p>
<%= render :partial=>"form" %>

app/views/users/reset.html.erb
<h1>Reset Your Password</h1>
<% @user.password = @user.password_confirmation = nil %>

<div class="form">
  <%= form_tag :action => 'reset' do |f| -%>
    <div class="settings_fields">
    <%= label_tag :password, 'Password' %>
    <%= password_field_tag :password, "", :class =>"formfield" %>
    </div>

    <div class="settings_fields">
    <%= label_tag :password_confirmation, 'Confirm' %>
    <%= password_field_tag :password_confirmation, "", :class =>"formfield" %>
    </div>

    <div>    
    <%= submit_tag 'Change Password' %>
    </div>
<% end -%>
</div>

app/views/users/show.html.erb
<%= content_for :head do %>
 <script type="text/javascript">
 var pageCount = 1;

  $(function(){
    $('#truth_form').jqEasyCounter({
		'maxChars': 180,
	    'maxCharsWarning': 165,
	    'msgFontSize': '15px',
	    'msgFontColor': '#005588',
	    'msgFontFamily': 'arial',
	    'msgTextAlign': 'left',
	    'msgWarningColor': 'red',
	    'msgAppendMethod': 'insertAfter'
    });

    $('textarea#truth_form').click(function () {
    	$(this).animate({ height: "80px" }, 200);
		});
  	
    $("#authenticate").click(function(){
      $.post('/microposts/create_pending', $("#new_micropost").serialize());
      return false;
    });

    $("#authenticate").fancybox({
      'transitionIn'    :    'elastic',
      'transitionOut'    :    'elastic',
      'speedIn'        :    400,
      'speedOut'        :    200,
      'overlayShow'    :    true
    });

    $(".post_comments").hide();
    	$(".microposts").delegate(".open_comments", "click", function(e){
	      $(this).next(".post_comments").slideToggle(300);
       e.preventDefault();
     });

    $('#pages_loading').hide();
    	$("#load-more").click(function(e){
    	$('#pages_loading').show();
      $.get(this.href, {page:pageCount+=1}, function(data) {
        var rows = $(data).find("#posts_table tr");
          $('#posts_table').append(rows);
          $(".post_comments").hide();
          $('#pages_loading').hide();
        });
      e.preventDefault();
    }); 

		$('#loading-animation').hide();
			$("#load_animate").click(function(){
      $('#loading-animation').show();
    });    
  });
</script>	 
<% end %>

<table class="profile_container" cellspacing="0">
	<td class="name_container">
		<div class="profile_name"> 
			<%= @user.username %> 
		</div>
		<div class="profile_stats">
			· <%= pluralize(@microposts.count, "Truth") %>
		</div>
		<div class="profile_stats">
			· <%= pluralize(@user.followers.count, "Follower") %> 
		</div>
		<div class="profile_avatar"> 
			<%= render_profile_pic(@user, :medium) %>	
		</div>
		<% if (@user == current_user) && (@user.blurb.blank?) %>
		<div class="profile_blurb"> 
			<%= link_to "Click here", edit_user_path(current_user) %> to add a profile blurb
		</div>
		<% else %>
		<div class="profile_blurb"> 
			<%= @user.blurb %> 
		</div>
		<% end %>
		<div class="profile_buttons">
		<% if current_user %>
			<% unless @user == current_user %>
				<%= render_follow_links(@user) %>
					<br/>
				<%= render 'notifications/new_notification' %>
					<p/>
			<% end %>
		<% end %>
		</div>
		<%= render 'shared/top_truth_feed' %>
		<div class="profile_side">
			<div class="profile_following-h">
				Following · <%= @user.following.count %>
			</div>
			<div class="profile_following">
 				<% unless @following.empty? %>
    			<% @following.each do |user| %>
	  				<div class="followings_avatar"><%= link_to render_follow_avatar(user, :tiny), user %></div>
	  				<div class="followings_username">
	  					<%= link_to user.username, user, :class => 'followlist_name', :style=>"color:#56A8CE;" %>
	  				</div> 
    			<% end %>
  			<% end %>
			</div>

			<div class="profile_following-h">
				Followers · <%= @user.followers.count %>
			</div>
			<div class="profile_followers">
				<% unless @followers.empty? %>
    			<% @followers.each do |user| %>
	   				<div class="followings_avatar"><%= link_to render_follow_avatar(user, :tiny), user %></div>
	   				<div class="followings_username">
	   					<%= link_to user.username, user, :class => 'followlist_name', :style=>"color:#56A8CE;" %>
	   				</div>
    			<% end %>
  			<% end %>
			</div>
		</div>
	</td>

	<td class="right_container">	
		<div class="newpost_container">
			<% if @user == current_user %>
				<div class="profile_feed_header">
					Truths about you
				</div>
			<% else %>
				<div class="profile_feed_header">
					What's the truth about <%= @user.username %>?
				</div>
			<% end %>
			<% unless @user == current_user %>
				<div class="micropost_form_container">
					<%= render 'microposts/form' %>
				</div>
				<div id="loading-animation">
					<div id="circleG">
						<div id="circleG_1" class="circleG"></div>
						<div id="circleG_2" class="circleG"></div>
						<div id="circleG_3" class="circleG"></div>
					</div>
				</div>
			<% end %>
		</div>
		<table class="microposts" id="posts_table">
			<% if @microposts.empty? %>
					<div class="profile_noshow">
						hmm no truths yet...
						<% if @user == current_user %>
							<div class="profile_noshow_content">
								<div class="step_number"> 1 </div>
								Share your profile URL with your friends to get truths. <strong>truthpage.me/<%= @user.username %></strong>
							</div>
							<div class="profile_noshow_content">
								<div class="step_number"> 2 </div>
								Find your <%= link_to "friends", root_url %> and write a truth about them.
							</div>
							<div class="profile_noshow_content">
								<div class="step_number"> 3 </div>
								Follow friends and rate or comment on truths about them!
							</div>
						<% end %>
					</div>
  		<% else %>
				<%= render @microposts  %>
			<% end %>
		</table>
		<% if @microposts.total_pages > 1 %>
			<div class="load_more_container">
  			<%= link_to "Load more", "#", :id=>"load-more" %>
  			<div id="pages_loading">
  				<div id="circleG">
						<div id="circleG_1" class="circleG"></div>
						<div id="circleG_2" class="circleG"></div>
						<div id="circleG_3" class="circleG"></div>
					</div>
  			</div>
  		</div>
		<% end %>
	</td>
</table>

app/views/users/show_follow.html.erb
<table summary="following/followers">
  <tr>
    <td class="main">
    <div class="dashfeed_header">  
	<strong><%= @user.username %></strong><%= @title %>
      </div>
      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Truths shared:</strong> <%= @user.microposts.count %> <br/>
	      <%= link_to "Find friends", search_url , :class =>"headerlink"%> <p/>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
        <% @users.each do |user| %>
		      <%= render_user_avatar(user, :thumb) %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>