config/routes.rb
Truthpage::Application.routes.draw do 
  
  match '/signin',  :to => 'sessions#new'
  match '/login',  :to => 'sessions#JSnew'
  match '/newlogin', :to => 'sessions#JScreate'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/welcome', :to => 'pages#welcome_page'
  match '/contact', :to => 'pages#contact'
  match '/home',   :to => 'pages#home'
  match '/about',  :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/legal',    :to => 'pages#legal'
  match '/privacy',    :to => 'pages#privacy'
  match '/terms',    :to => 'pages#terms'
  match '/help',    :to => 'pages#help'
  match '/admin', :to => 'admin/users#index'
  match '/',        :to => 'pages#home'
  match '/tickertest', :to=>'pages#tickertest'
  match "/auth/:provider/callback" => "authentications#create"
  match "/auth/failure" => "authentications#auth_failure"
  match "/search", :to=> "users#index", :as=>"search" 
  match '/activate/:id/:activation_code', :to=>"users#activation", :as=>"activate"
  match "/assist", :to=>"users#assist", :as=>"assist"
  match "/reset/:id/:reset_code", :to=>"users#reset", :as=>"reset"
  match "/activate_user/:id", :to=>"users#activate", :as=>"activate_user"
  match "/welcome_user/:id", :to=>"users#welcome", :as=>"welcome_user"
  match "complete_session_authentication_path", :to=>"authentications#complete_session_authentication", :as=>:complete_session_authentication
             
  resources :microposts do
    collection do
      post :create_pending
    end
    resources :comments
  end
  resources :users do
      member do
        post :follow
        post :unfollow
        get :following, :followers
        delete :remove_background
        delete :remove_photo
        delete :deactivate_profile
      end
  end
  resources :notifications, :only=>[:create, :destroy] do
    collection do
      delete :clear_all
    end
  end
  resources :ratings, :only => [:create, :destroy]
  resources :authentications
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :comments, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  namespace :admin do
    resources :users
  end

  controller :users do
    match ':id' => :show, :via => :get, :constraints => { :id => /[A-Za-z0-9\-\_\+]+/ }
  end

  root :to => 'pages#home'

end

app/views/pages/_authenticated_home.html.erb
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script type="text/javascript">
 var pageCount = 1;
	$(function(){
		$(".post_comments").hide();
    	$(".open_comments").click(function(e){
      	$(this).next(".post_comments").slideToggle(300);
      	e.preventDefault();
    });

    $('#pages_loading').hide();
    	$("#load-more").click(function(e){
    	$('#pages_loading').show();
      $.get(this.href, {page:pageCount+=1}, function(data) {
        var rows = $(data).find("#posts_table tr");
          $('#posts_table').append(rows);
          $(".post_comments").hide();
          $('#pages_loading').hide();
        });
      e.preventDefault();
    }); 

		$("#share_profile").click(function() {
		FB.init({ 
		  appId:'186414394781001', 
		  channelUrl : '//truthpage.me/channel.html', // Channel File
			status     : true, // check login status
			cookie     : true, // enable cookies to allow the server to access the session
			xfbml      : true  // parse XFBML
		});
		FB.ui( {
			method: 'feed',
			name: 'Whats the real truth about me? Be honest. truthpage.me/<%= current_user.username %>',
			caption: 'Post a truth about me on truthpage.me',
			link: '<%= root_url%><%= current_user.username %>',
			actions: [
				{ name: 'truthpage.me', link: 'http://truthpage.me' }
					],
				user_message_prompt: 'Share a truth status'
				},
			function(response) {
				if (response && response.post_id) {
				} else {
				}
				}
			);
		});
	});

function tweetpopup() {

window.open( "http://twitter.com/share?url=<%= root_url%><%= current_user.username %>&text=Whats%20the%20real%20truth%20about%20me?%20Be%20honest.&count=none/", "tweet", "height=450,width=550,resizable=1" ) 
}
</script>

<div id="fb-root">
  <script src="http://connect.facebook.net/en_US/all.js"></script>
  <script>
      $(function sendRequestViaMultiFriendSelector(){
      $("a#invite_fb_friends").click(function(event) {
        FB.ui({
        method: 'apprequests',
        message: 'Whats the truth about me? Be honest. truthpage.me/<%= current_user.username %>'});
        event.preventDefault();
        return false;
      });
     });
  </script>
</div>

<table class="friends_container" cellspacing="0">
  <tr>
    <td class="friends-left">
			<div class="dash_column">
				<div class="friends_column_share">
					Your profile URL
				</div>
				<div class="share_profile_url">
					<span class="share_url_span">truthpage.me/</span><%= current_user.username %>
				</div>
				<div class="friends_column_h">
					Share your profile
				</div>
				
		    		<%= link_to "Share on Facebook", "#", :id => "share_profile", :class => 'facebook_share', :style=>'color:#FFFFFF;' %>
					
						<a href="http://twitter.com/share?url=url_you_wish_the_tweet_to_link_back_to&text=the%20text%20you%20wish%20the%20tweet%20to%20say&count=none/" class="custom-tweet-button" target="_blank" onClick="tweetpopup(); return false;" rel="nofollow" style="color:#FFFFFF;">Share on Twitter</a>

				<%# unless current_user.authentications.empty? %>
					<%# render 'shared/fb_truth_feed' %>
				<%# end %>
				<div class="fb_feed_friends">
					Friends on truthpage.me
				</div>
				<%= link_to '+ Invite Facebook Friends', '#' , :id => 'invite_fb_friends', :class => 'facebook_invite', :style=>'color:#FFFFFF;'  %> 
				<% unless current_user.authentications.empty? %>
					<% if @registered_friends.empty? %>
						<div class="fb_friends_noshow">
							None of your Facebook friends have a truthpage yet...
						</div>
					<% else %>
						<div class="fbfriends_box">
  						<% @registered_friends.each do |user| %>
  							<div class="fbfriend_block">
      						<%= link_to render_user_avatar(user, :thumb), user.username %>
      						<div class="fbfriend_username"><%= link_to user.username, user.username, :style=>"color:#56A8CE;" %></div>
  							</div>
  						<% end %>
						</div>
					<% end %>
				<% else %>
					<div class="fb_friends_noshow_fb">
				  	<%= render :partial=>"authentications/services" %>
				  </div>
				  <div class="fb_friends_noshow">
						Connect with Facebook to see your friends on truthpage.me!
					</div>
				<% end %>
			</div>
			</td>
			<td class ="dash_right_cell">
				<% if @change_feed_header %>
					<div class="dashfeed_title">
        		Truths about your Facebook friends
      		</div>
      	<% else %>
      		<div class="dashfeed_title">
        		Truths about friends you're following
      		</div>
      	<% end %>
			<div class="dashfeed_content">
				<%= render 'shared/feed' %>
			</div>
			</td>
    </td>
  </tr>
</table>

app/views/pages/_unauthenticated_home.html.erb
<%= content_for :head do %>
  <script type="text/javascript">
    $(function(){
      $('#vertical-ticker').totemticker({
		    row_height  :   '55px',
        next        :   '#ticker-next',
        previous    :   '#ticker-previous',
        stop        :   '#stop',
		start       :   '#start',
		direction   :   'up',
		speed       :   1000,
		interval    :   5000
        });
    });
  </script>
<% end %>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=186414394781001";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<div class="header_box">
  <h1>Get truths about yourself, from your friends.</h1>
  <div class="header_body">
    truthpage.me is a fun and easy way to share and rate truths about your friends.
  </div>
</div>

<div class="ticker_header">
  Most recent truths on truthpage.me
</div>
	
<ul id="vertical-ticker" style="overflow-x: hidden; overflow-y: hidden; ">
  <% for mp in Micropost.all.take(50) do %>  
    <li><%= render :partial=>"microposts/ticker_micropost", :locals=>{:micropost=>mp} %></li>
  <% end %>
</ul>

<div class="home_signup_box">
  <h1>Sign in</h1>
  <div class="signup_box_fbconnect">
    <%= render :partial=>"authentications/services" %>
  </div>
  <div class="home_signin_or">
    or
  </div>
  <%= form_tag sessions_path do %>
      <div class="home_signin_field">
        <div class="home_formlabel">Username / Email</div>
        <%= text_field_tag :login, params[:login], :class => "home_formfield", :id => "SAusername" %>
      </div>
      <div class="home_signin_field">
        <div class="home_formlabel">Password</div>
        <%= password_field_tag :password, "", :class => "home_formfield", :id => "SApassword" %>
      </div>
      <%= link_to "Forgot your Password?", assist_url, :id=>"forgot-password", :class =>"home_signin_forgotpw" %> 
        <br/>
      <div class="home_signin_button_placement">
        <%= submit_tag "Sign in", :class=>'signin_button' %>
      </div>
  <% end %>
</div>

<div class="home_facepile">
  <div class="home_facepile_box">
    <h1>Recently joined</h1>
    <% @faces.each do |user| %>
      <div class="fbfriend_block">
        <%= link_to render_user_avatar(user, :thumb), user.username %>
        <div class="fbfriend_username"><%= link_to user.username, user.username %></div>
      </div>
    <% end %>
  </div>
</div>


<div class="social_network_buttons_container">
  <div class="social_network_buttons">
    <g:plusone annotation="inline">
    </g:plusone>

    <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://truthpage.me" data-text="Get truths about yourself, from your friends." data-hashtags="truthpage.me">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
    </script>

    <a href="http://www.tumblr.com/share" title="Share on Tumblr" style="display:inline-block; text-indent:-9999px; overflow:hidden; width:81px; height:20px; background:url('http://platform.tumblr.com/v1/share_1.png') top left no-repeat transparent;">Share on Tumblr</a>

    <div class="fb-like" data-href="http://truthpage.me" data-send="true" data-width="450" data-show-faces="false" data-action="recommend" data-font="tahoma"></div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="footer_container">

	<div class="fhead">truthpage.me</div>

	<div class="fsub">© 2011 – 2012</div>

	<div class="fsub">About</div>

	<div class="fbody2">
		truthpage.me is a site allowing users to share truths with their friends in a fun, easy, simple, and concise manner. We look toward the simplicity of the conventions found on our site to enhance the social experience of our users.
		<p/>

		<p>
		Created in good taste by Chris Scutti and Brock Harris.
		</p>

		<p>
		Special thanks to Mike DelGrosso for his remarkable guidance in the final stages of development.
		<p/>

		<p>
		truthpage.me is hosted in Houstatlantavegas.
		<p/>

		<p>
		For any questions, comments, or general contact inquiries, send us an email at support@truthpage.me.
		</P>
	</div>
</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<div class="footer_container">

	<div class="fhead">truthpage.me</div>

	<div class="fsub">© 2011 – 2012</div>

	<div class="fsub">Help</div>
	
	<div class="fbody">
	</p>
	Welcome to truthpage.me!
	</p>
	Once you’re signed in, share your profile with your friends via Facebook and Twitter.
	<p/>
	Then, navigate to your friends' profiles and leave truths about them!
	<p/>
	Each truth you post and each truth your followed friends post will display in the feed on your Friends page.
	<p/>
	Have questions or comments? Leave us feedback via chris@truthpage.me or brock@truthpage.me. We look forward to hearing from you!
	</div>
</div>

app/views/pages/home.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26913646-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=186414394781001";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

<script 
type="text/javascript" src="http://platform.tumblr.com/v1/share.js">
</script>


<% if current_user %>
	<%= render 'pages/authenticated_home' %>
<% else %>
	<%= render 'pages/unauthenticated_home'%>
<% end %>

app/views/pages/legal.html.erb
<div class="footer_container">

	<div class="fhead">truthpage.me</div>

	<div class="fsub">© 2011 – 2012</div>

<div class="fsub">Copyright Notice</div>

<p/>

<div class="fbody">
All materials contained on truthpage.me are protected by the accompanying copyright laws, and are the sole property of our partnership. They may not be reproduced, republished, distributed, transmitted, displayed, broadcast, forwarded or otherwise exploited in any manner whatsoever without the expressed prior written consent of truthpage.me and its founding partners.
<p/>
<div class="fsub">Intellectual Property Notice</div>
<p/>
Our founding development partnership hereby declares that we are the original proprietors of the idea and any images, URLs, web forms, features, conventions and schemas found or contained in truthpage.me. We also declare that we are the sole holding proprietors of material formatted, added, and/or modified throughout overall site development from inception to launch.
<p/>
Furthermore, any material found on truthpage.me involving front and/or back-end site source code is the sole property of truthpage.me and its founding partners.
<p/>
Any attempted, outside, unauthorized attempt to reproduce, modify, change, add or subtract our founding ideas, use cases, material, web forms, schematics, URLs, images, user accounts, or any other element contained and held legally proper by truthpage.me and its founding partners will be address to the fullest extent of governing legal jurisdiction.
<p/>
Any legal inquiries regarding truthpage.me and any of its materials, site content, copyrights, domains, or any other legal matter pertaining hereto, may be directed to chris@truthpage.me.
<p/>
Our founding partnership would like to personally thank you for being a part of the truthpage.me experience.
</div>

app/views/pages/privacy.html.erb
<div class="footer_container">

	<div class="fhead">truthpage.me</div>

	<div class="fsub">© 2011 – 2012</div>

	<div class="fsub">Privacy Policy</div>

	<div class="fbody">
	We collect a minimal amount of information about you as a user of truthpage.me. This information includes, but is not limited to, your name, email, and birthday. Your site-designated username will be seen by other users of truthpage.me. No unauthenticated viewer of truthpage.me content will see your email outside the conventions of our site. We will never share any of your personal information with anyone or any institution under any circumstance. 
	<p/>
	In accordance with the Children’s Online Privacy and Protection Act of 1998, truthpage.me will never acknowledge the receipt of information from children under the age of 13. Any otherwise intended misuse of an account to designate or procure this information is prohibited and punishable by law.
	<p/>
	Any password you may choose to set for your truthpage.me account is protected via layered authentication and encryption. This password is the property of the user who created it. The truthpage.me team does not have access to your password.
	<p/>
	The custom user URL that is generated for you when signing up for a truthpage.me account is open to anyone on the World Wide Web. Any web user will be able to view your profile and any of its contents, but will not be able to post anything to your profile until properly authenticated as an actual truthpage.me user.
	<p/>
	We reserve the right to modify or change completely any username for any reason, at any time. to any other available username site-wide. This will change the automatically generated URL, and thus any username changes are publicly viewable.
	<p/>
	Embedded Twitter and Facebook authentication methods will pull data from your Twitter or Facebook profiles only upon your approval of these aforementioned services establishing a connection to your account.
	<p/>
	If you choose to discontinue your truthpage.me account at any point, any submitted information will be subsequently deleted from our records. If you, as a user of turthpage.me, click on any other site-embedded service (Facebook share, Tweet, Google Plus share, and Tumblr share) and are prompted for any personal information or any otherwise personal details via that link, we will not be held liable for any privacy issue(s) pertaining thereto.
	<p/>
	We have established this policy to ensure that the integrity of your rights as a user are upheld to the fullest extent.
	</p>
	Any questions, comments, or general inquiries regarding the truthpage.me privacy policy should be directed to support@truthpage.me. 
	</div>
</div>

app/views/pages/terms.html.erb
<div class="footer_container">

	<div class="fhead">truthpage.me</div>

	<div class="fsub">© 2011 – 2012</div>

	<div class="fsub">Terms of Use</div>

	<div class="fbody">
	By using truthpage.me you agree to the following: 
	</p>
	That you are at least 13 years of age, in line with the Children’s Online Privacy Protection Act of 1998. 
	</p>
	To conduct yourself in an appropriate manner pertaining to site-containing elements, and ensure that any behavior and actions taken on truthpage.me are in line with the legal jurisdiction of your location.
	</p>
	To use truthpage.me solely for its intended usages. Any unorthodox misuse of truthpage.me absent of these intended usages will be subject to immediate termination of user account and legal action to the fullest extent of governing laws.
	</p>
	Under no circumstances shall truthpage.me, its founding partners or any of its respective contingencies, shareholders, agents or representatives be held liable for any damages incurred to you or any user, direct, indirect, special or consequential, resulting from user misuse of the site and any of its overall conventions put forth, in any circumstance.
	</div>
</div>

app/views/pages/welcome_page.html.erb
<div class="welcome_banner">
	<h1>Welcome to truthpage.me!</h1>
	<h2>a sub-header can go here.</h2>
</div>
<div class="step_container">
	<h2>1</h2>
	<h1>Share your profile url: truthpage.me/(<%= current_user.username %>)</h1>
</div>
<div class="step_container">
	<h2>2</h2>
	<h1>Find your <%= link_to "friends", root_url %> and write a truth about them.</h1>
</div>
<div class="step_container">
	<h2>3</h2>
	<h1>Follow your friends,</h1>
</div>