config/routes.rb
Truthpage::Application.routes.draw do 
  
  match '/signin',  :to => 'sessions#new'
  match '/login',  :to => 'sessions#JSnew'
  match '/newlogin', :to => 'sessions#JScreate'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/welcome', :to => 'pages#welcome_page'
  match '/contact', :to => 'pages#contact'
  match '/home',   :to => 'pages#home'
  match '/about',  :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/legal',    :to => 'pages#legal'
  match '/privacy',    :to => 'pages#privacy'
  match '/terms',    :to => 'pages#terms'
  match '/help',    :to => 'pages#help'
  match '/admin', :to => 'admin/users#index'
  match '/',        :to => 'pages#home'
  match '/tickertest', :to=>'pages#tickertest'
  match "/auth/:provider/callback" => "authentications#create"
  match "/auth/failure" => "authentications#auth_failure"
  match "/search", :to=> "users#index", :as=>"search" 
  match '/activate/:id/:activation_code', :to=>"users#activation", :as=>"activate"
  match "/assist", :to=>"users#assist", :as=>"assist"
  match "/reset/:id/:reset_code", :to=>"users#reset", :as=>"reset"
  match "/activate_user/:id", :to=>"users#activate", :as=>"activate_user"
  match "/welcome_user/:id", :to=>"users#welcome", :as=>"welcome_user"
  match "complete_session_authentication_path", :to=>"authentications#complete_session_authentication", :as=>:complete_session_authentication
             
  resources :microposts do
    collection do
      post :create_pending
    end
    resources :comments
  end
  resources :users do
      member do
        post :follow
        post :unfollow
        get :following, :followers
        delete :remove_background
        delete :remove_photo
        delete :deactivate_profile
      end
  end
  resources :notifications, :only=>[:create, :destroy] do
    collection do
      delete :clear_all
    end
  end
  resources :ratings, :only => [:create, :destroy]
  resources :authentications
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :comments, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  namespace :admin do
    resources :users
  end

  controller :users do
    match ':id' => :show, :via => :get, :constraints => { :id => /[A-Za-z0-9\-\_\+]+/ }
  end

  root :to => 'pages#home'

end

app/views/layouts/_admin_header.html.erb
<div class="header_bar">
<ul class="header_text">
  <li>
    <%= link_to "truthpage.me", root_path %>
  </li>
</ul>
  <nav class="round">
    <ul class="header_nav">
      <div class="headerlink_place">
        <% if current_user %>
          <li><%= link_to "Friends", root_url, :class =>"header_links" %></li> 
          <li><%= link_to "Profile", "#{ root_url }#{ current_user.username }" , :class =>"header_links" %></li> 
          <li><%= link_to "Settings", edit_user_path(current_user), :class =>"header_links" %></li> 
          <li><%= link_to "Sign out", signout_path, :class =>"header_links", :method => :delete %></li>
        <% else %>
          <li><%= link_to "Home", root_path, :class =>"header_links" %></li> 
          <li><%= link_to "Sign up", newlogin_path, :id =>"signup", :class =>"header_links" %></li>
        <% end %>
      </div>
    </ul>
  </nav>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
    	<div class="footer_bg">
			<li><%= link_to "truthpage.me © 2012", root_path, :class => "footer_links"  %></li> ·
			<li><%= link_to "about", about_path, :class => "footer_links"  %></li> ·
      <li><%= link_to "privacy policy", privacy_path, :class => "footer_links"  %></li> ·
			<li><%= link_to "terms of use", terms_path, :class => "footer_links" %></li> ·
			<li><%= link_to "legal", legal_path, :class => "footer_links"  %></li> ·
			<li><%= link_to "help", help_path, :class => "footer_links"  %></li>
		  <% if current_user.try(:admin?) %> · 
				<li><%= link_to "admin", admin_path, :class => "footer_links" %></li>
      <% end %>
      </div>
    </ul>
  </nav>
</footer>
<%# debug session if Rails.env=="development" %>

app/views/layouts/_header.html.erb
<script type="text/javascript">
  $(function(){
    $('#flash').delay(2000).fadeIn('normal', function() {
      $(this).delay(2000).fadeOut();
   });

    $("#signin").fancybox({
      'transitionIn'    :    'elastic',
      'transitionOut'    :    'elastic',
      'speedIn'        :    400,
      'speedOut'        :    200,
      'overlayShow'    :    true
    });

    $("#signup").fancybox({
      'transitionIn'    :    'elastic',
      'transitionOut'    :    'elastic',
      'speedIn'        :    400,
      'speedOut'        :    200,
      'overlayShow'    :    true
    });

    $('.noty_menu').click(function () {
      $('ul.the_menu').slideToggle('medium');
      return false;
    });

    $('body').click(function() {
      $('ul.the_menu').slideUp(150);
    });
  });
</script> 

<div class="header_bar">
  <ul class="header_text">
    <li>
      <%= link_to "truthpage.me", root_path %>
    </li>
  </ul>
  <nav class="round">
    <ul class="header_nav">
      <div class="headerlink_place">
        <% if current_user %>
          <li><%= link_to "Friends", root_url, :class =>"header_links" %></li> 
          <li><%= link_to "Profile", "#{ root_url }#{ current_user.username }" , :class =>"header_links" %></li> 
          <li><%= link_to "Settings", edit_user_path(current_user), :class =>"header_links" %></li> 
          <li><%= link_to "Sign out", signout_path, :class =>"header_links", :method => :delete %></li>
        <% else %>
          <li><%= link_to "Home", root_path, :class =>"header_links" %></li> 
		      <li><%= link_to "Sign up", newlogin_path, :id =>"signup", :class =>"header_links" %></li>
        <% end %>
      </div>
    </ul>
  </nav>
  <% if current_user %>
    <ul class="the_menu">
      <div class="menu_header">
        Notifications - <%= notifications.count %>
      </div>
      <li>
        <%= render notifications %>
      </li>
      <div class="notification_clear_all">
        <%= button_to "Clear all", clear_all_notifications_path, :method=>:delete, :class=>'notification_clear_all_button' %>
      </div>
    </ul> 
    <div class="welcome_user_avatar">
        <%= render_user_avatar(current_user, :tiny) %>
    </div>
    <div class="welcome_user_text">
        <%= link_to "#{ current_user.username }", "#{ root_url }#{ current_user.username }", :style=>'color:#EEEEEE;' %>
    </div>
    <% unless notifications.empty? %> 
      <div class="bubble_placement">
        <%= link_to "#{ notifications.count}", "#", :class=> "noty_menu", :style=>'color:#FFFFFF;' %>
      </div>
    <% end %>
  <% end %>
  <% flash.each do |key, value| %>
    <div id="flash" class="<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag "application"%>
    <%= stylesheet_link_tag "application", :media => "all" %>    
    <%= yield :head %>
  </head>
  <% unless @user_custom_background %>
    <body> 
  <% else %>
    <body style="background-image:url(<%= @user.background.url %>); background-repeat:repeat;">
  <% end %>
    <%= render 'layouts/header' unless @skip_render %>
    <%= render 'layouts/admin_header' if @render_admin_header %>
      <div class="container">
	      <section class="round">
	      <%= yield %>
	    </section>
      <%= render 'layouts/footer' unless @skip_render %>
    </div>
  </body>
</html>